language: python

jobs:
  include:
    - name: "Windows"
      os: windows
      language: shell
      env:
        - PYTHON_BIN=python
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - echo $SIGN_WIN_CERT | base64 --decode > cert.pfx
        - powershell //C "\$Password = ConvertTo-SecureString $SIGN_WIN_PASS -AsPlainText -Force; echo \$Password; Import-PfxCertificate -FilePath cert.pfx -CertStoreLocation Cert:\LocalMachine\My -Password \$Password"
        - choco install -y python --no-progress --version 3.8.6
        - choco install -y nsis
        - cd "C:/Program Files (x86)/NSIS"
        - wget --quiet https://nsis.sourceforge.io/mediawiki/images/4/4a/AccessControl.zip
        - unzip -qq AccessControl.zip
        - rm AccessControl.zip

install:
  - cd $TRAVIS_BUILD_DIR
  - $PYTHON_BIN -m pip install --upgrade pip setuptools wheel
  - $PYTHON_BIN -m pip install --upgrade requests pyinstaller
  - $PYTHON_BIN -m pip install -r requirements.txt

script:
  - cd $TRAVIS_BUILD_DIR/scripts
  - ./build.bat