name: Autobuild

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Import certificate
        shell: bash
        run: >
          echo ${{ secrets.SIGN_WIN_CERT }} | base64 --decode > cert.pfx &&
          powershell //C "\$Password = ConvertTo-SecureString ${{ secrets.SIGN_WIN_PASS }} -AsPlainText -Force; echo \$Password; Import-PfxCertificate -FilePath cert.pfx -CertStoreLocation Cert:\LocalMachine\My -Password \$Password"
      - name: Install NSIS plugins
        shell: bash
        working-directory: "C:/Program Files (x86)/NSIS"
        run: >
          wget --quiet https://nsis.sourceforge.io/mediawiki/images/4/4a/AccessControl.zip &&
          unzip -qq AccessControl.zip &&
          rm AccessControl.zip
      - name: Install requirements
        shell: bash
        run: >
          python -m pip install --upgrade pip setuptools wheel &&
          python -m pip install --upgrade requests pyinstaller &&
          python -m pip install -r requirements.txt
      - name: Build executable
        shell: powershell
        working-directory: ./scripts
        env:
          SIGN_WIN_TIMESTAMP: ${{ secrets.SIGN_WIN_TIMESTAMP }}
          SIGN_WIN_SUBJECT: ${{ secrets.SIGN_WIN_SUBJECT }}
          DEPLOY_ENDPOINT: ${{ secrets.DEPLOY_ENDPOINT }}
          DEPLOY_LOGIN: ${{ secrets.DEPLOY_LOGIN }}
        run: >
          ./build.bat