name: Autobuild

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Import certificate
        shell: bash
        run: >
          echo ${{ secrets.SIGN_WIN_CERT }} | base64 --decode > cert.pfx &&
          powershell //C "\$Password = ConvertTo-SecureString ${{ secrets.SIGN_WIN_PASS }} -AsPlainText -Force; echo \$Password; Import-PfxCertificate -FilePath cert.pfx -CertStoreLocation Cert:\LocalMachine\My -Password \$Password"
      - name: Download AccessControl
        uses: suisei-cn/actions-download-file@v1
        with:
          url: https://nsis.sourceforge.io/mediawiki/images/4/4a/AccessControl.zip
          target: "C:/Program Files (x86)/NSIS"
      - name: Install AccessControl
        shell: bash
        working-directory: "C:/Program Files (x86)/NSIS"
        run: >
          unzip -qq AccessControl.zip &&
          rm AccessControl.zip
      - name: Install Python requirements
        shell: bash
        run: >
          python -m pip install --upgrade requests git+https://github.com/3wnbr1/pyinstaller@pyside6 &&
          python -m pip install -r requirements.txt
      - name: Build executable
        shell: powershell
        working-directory: ./scripts
        env:
          SIGN_WIN_TIMESTAMP: ${{ secrets.SIGN_WIN_TIMESTAMP }}
          SIGN_WIN_SUBJECT: ${{ secrets.SIGN_WIN_SUBJECT }}
          DEPLOY_ENDPOINT: ${{ secrets.DEPLOY_ENDPOINT }}
          DEPLOY_LOGIN: ${{ secrets.DEPLOY_LOGIN }}
        run: >
          ./build.bat
